name: "[MAIN] Publish Chat Gateway Docker image"
on:
  push:
    branches:
      - main
      - cicd
    paths-ignore:
      - "README.md"
      - "LICENSE"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(grep -m1 'version = ' pyproject.toml | cut -d '"' -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Generate metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.extract_version.outputs.version }}
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
  update-helm-charts:
    name: Update Helm Charts
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/cicd')
    
    env:
      HELM_REPO: CraftSchoolship/deployment-configs
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_APP_ID }}
          private-key: ${{ secrets.GITOPS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
        
      - name: Checkout Helm Charts Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.HELM_REPO }}
          token: ${{ steps.app-token.outputs.token }}
          ref: main
      
      - name: Update Image Tag
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          yq -i '.image.tag = "${{ needs.build-and-push-image.outputs.image_tag }}"' spoutbreeze/chat-gateway/values.yaml

      - name: Create Branch and Push
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="update-image-tag-${{ needs.build-and-push-image.outputs.image_tag }}"
          git config --global user.email "bot@spoutbreeze.com"
          git config --global user.name "SpoutBreeze Bot"
          
          git checkout -b "$BRANCH_NAME"
          git add spoutbreeze/chat-gateway/values.yaml
          git commit -m "chore: update spoutbreeze image to ${{ needs.build-and-push-image.outputs.image_tag }}"
          git push origin "$BRANCH_NAME"

          gh pr create \
            --repo CraftSchoolship/deployment-configs \
            --title "Deploy SpoutBreeze ${{ needs.build-and-push-image.outputs.image_tag }}" \
            --body "Automated update from CI pipeline." \
            --base main \
            --head "$BRANCH_NAME"